COMPILLER = g++
FLAGS = -pthread -std=c++11
FILES = OOP9.cpp figure_pentagon.cpp figure_octagon.cpp figure_hexagon.cpp
NAME = OOP9.out

all:
	$(COMPILLER) $(FILES) -o $(NAME) $(FLAGS)
clean:
	rm -f *.o $(NAME)