COMPILLER = g++
FLAGS = -std=c++11 -o
FILES = OOP7.cpp TAllocationBlock.cpp TVector.cpp TVectorItem.cpp figure_pentagon.cpp figure_octagon.cpp figure_hexagon.cpp TStack.cpp TStackItem.cpp
NAME = OOP7

all:
	$(COMPILLER) $(FLAGS) $(NAME) $(FILES)
clean:
	rm -f *.o $(NAME)