COMPILLER = g++
FLAGS = -pthread -std=c++11
FILES = OOP8.cpp TAllocationBlock.cpp TVector.cpp TVectorItem.cpp figure_pentagon.cpp figure_octagon.cpp figure_hexagon.cpp TStack.cpp TStackItem.cpp
NAME = OOP8.out

all:
	$(COMPILLER) $(FILES) -o $(NAME) $(FLAGS)  
clean:
	rm -f *.o $(NAME)
